aliases: []
creation_timestamp: 1740674768705
current_stage: None
description: null
last_updated_timestamp: 1740674768705
name: SpamClassifierModel
run_id: 702a734a21fe45eba2518357a9573166
run_link: null
source: file:///c:/Users/naren/OneDrive/Documents/CMI/Semester 4/Applied Machine Learning/Assignment_2/mlruns/712774972690327265/702a734a21fe45eba2518357a9573166/artifacts/model
status: READY
status_message: null
storage_location: file:///c:/Users/naren/OneDrive/Documents/CMI/Semester 4/Applied
  Machine Learning/Assignment_2/mlruns/712774972690327265/702a734a21fe45eba2518357a9573166/artifacts/model
user_id: null
version: 6
