aliases: []
creation_timestamp: 1740674746026
current_stage: None
description: null
last_updated_timestamp: 1740674746026
name: SpamClassifierModel
run_id: 642d62462aaf4a58864dbc1a8f837229
run_link: null
source: file:///c:/Users/naren/OneDrive/Documents/CMI/Semester 4/Applied Machine Learning/Assignment_2/mlruns/712774972690327265/642d62462aaf4a58864dbc1a8f837229/artifacts/model
status: READY
status_message: null
storage_location: file:///c:/Users/naren/OneDrive/Documents/CMI/Semester 4/Applied
  Machine Learning/Assignment_2/mlruns/712774972690327265/642d62462aaf4a58864dbc1a8f837229/artifacts/model
user_id: null
version: 4
