aliases: []
creation_timestamp: 1740669257987
current_stage: None
description: null
last_updated_timestamp: 1740669257987
name: SpamClassifierModel
run_id: d1df0f4f00c24fcc8128171054513663
run_link: null
source: file:///c:/Users/naren/OneDrive/Documents/CMI/Semester 4/Applied Machine Learning/Assignment_2/mlruns/712774972690327265/d1df0f4f00c24fcc8128171054513663/artifacts/model
status: READY
status_message: null
storage_location: file:///c:/Users/naren/OneDrive/Documents/CMI/Semester 4/Applied
  Machine Learning/Assignment_2/mlruns/712774972690327265/d1df0f4f00c24fcc8128171054513663/artifacts/model
user_id: null
version: 3
