artifact_location: file:///c:/Users/naren/OneDrive/Documents/CMI/Semester 4/Applied
  Machine Learning/Assignment_2/mlruns/0
creation_time: 1740668958801
experiment_id: '0'
last_update_time: 1740668958801
lifecycle_stage: active
name: Default
